const router = require("express").Router();
const auth = require("../middleware/auth");
const { uploadAudio } = require("../middleware/uploadAudio");
const c = require("../controllers/coachingController");
router.use("/coaching", auth);
router.get("/coaching", c.dashboard);
router.get("/coaching/history", c.history);
router.put("/coaching/profile", c.saveProfile);
router.get("/coaching/coaches", c.coaches);
router.get("/coaching/inbox", c.expertInbox);
router.put("/coaching/availability", c.availability);
router.post("/coaching/sessions", uploadAudio, c.submit);
router.get("/coaching/sessions/:id", c.getSession);
router.get("/coaching/sessions/:id/audio", c.audio);
router.patch("/coaching/sessions/:id", c.updateSession);
router.delete("/coaching/sessions/:id", c.remove);
router.post("/coaching/sessions/:id/followup", c.followup);
router.post("/coaching/sessions/:id/review-request", c.requestReview);
router.post("/coaching/sessions/:id/review", c.review);
router.post("/coaching/sessions/:id/review-question", c.reviewQuestion);
router.post("/coaching/sessions/:id/review-answer", c.reviewAnswer);
module.exports = router;
